---
title: "p8105_hw3"
author: "Si Li"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(dplyr)
library(tidyverse)
```

Problem 1
```{r}
library(p8105.datasets)
data("instacart")
instacart %>% 
  summarise(n_aisle= n_distinct(aisle))

ais_n=
instacart %>% 
  count(aisle, name = "number")%>% 
  arrange(desc(number))
ais_n

instacart %>% 
  count(aisle, name = "number")%>% 
  filter(number>10000)%>% 
  ggplot(aes(aisle, number, label=number))+
  geom_bar(stat="identity",position="dodge")+
  ggtitle("The number of times ordered in each aisle")+
  coord_flip()

instacart %>%
  count(aisle, name = "n_times") %>% 
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>% 
  knitr::kable()

instacart %>% 
  group_by(product_name,order_dow) %>% 
  select(product_name, order_dow, order_hour_of_day) %>% 
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  summarise(mean_order_hour=mean(order_hour_of_day)) %>% 
  mutate(order_dow = recode(order_dow, `0` ="Sun", `1` = "Mon", `2`= "Tues", `3`= "Wed", `4` = "Thurs", `5`= "Fri", `6`= "Sat")) %>% 
  pivot_wider(names_from = order_dow,
              values_from = mean_order_hour)%>% 
  knitr::kable()
```